version: '3'

services:
  app:
    container_name: 'Dashboard_on'
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - tailwind.config.js:/app/tailwind.config.js
    environment:
      - PORT=4001
    ports:
      - "8092:4001"
    # command: npm install cookie-parser && npm start
    networks:
      - backend_network
  
volumes:
  node_modules:

networks:
  backend_network:
    driver: bridge
